CREATE DATABASE IF NOT EXISTS pet_health
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'pet_health_app'@'localhost' IDENTIFIED BY 'REPLACE_WITH_STRONG_PASSWORD';
CREATE USER IF NOT EXISTS 'pet_health_app'@'127.0.0.1' IDENTIFIED BY 'REPLACE_WITH_STRONG_PASSWORD';

GRANT ALL PRIVILEGES ON pet_health.* TO 'pet_health_app'@'localhost';
GRANT ALL PRIVILEGES ON pet_health.* TO 'pet_health_app'@'127.0.0.1';
FLUSH PRIVILEGES;
